FROM node:20

WORKDIR /app

ENV NODE_ENV=development

# فقط dependency ها برای cache بهتر
COPY frontend/package*.json ./

RUN npm cache clean --force \
    && npm install --legacy-peer-deps

# بعد کل پروژه
COPY frontend/.  .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
